server {
  listen 8080;
  server_name _;

  access_log off;

  location = / {
    if ($arg_domain ~* "^p-[0-9a-f-]+[.]webstudio[.]agnsbroadband[.]in$") {
      return 200;
    }

    return 403;
  }
}
